{% set name = "pysoundcard" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/soundcard/SoundCard-{{ version }}.tar.gz
  sha256: 410835514ba10809803cb9887d4270f392b59eaf365915bb94516af3f8b1d037

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - __linux     # [linux]
    - __osx       # [osx]
    - __win       # [win]
    - pulseaudio  # [linux]
    - numpy
    - cffi

test:
  imports:
    - soundcard
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bastibe/SoundCard
  summary: Play and record audio without resorting to CPython extensions
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
