{% set name = "pysoundcard" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/soundcard/soundcard-{{ version }}.tar.gz
  sha256: 87df9c4b8ec97585fe440a1d9dbafabcece58eae5857ed005e6bb385b2179cff

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - __linux     # [linux]
    - __osx       # [osx]
    - __win       # [win]
    - pulseaudio  # [linux]
    - numpy
    - cffi >=0.6

test:
  imports:
    - soundcard
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bastibe/SoundCard
  summary: Play and record audio without resorting to CPython extensions
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
